---
title: "ecls"
output: html_document
date: "2025-03-10"
---

# ECLS-K 
```{r} 
source("../../setup/external.R")
output_path <- "../output/"

##########################
# Set up
##########################

# Original K-8 Sample 
ecls <- read_dta(file.path(external_path, "ecls/ECLSK_Kto8_child_STATA.dta"))
save(ecls, file = file.path(external_path, "ecls/raw_ecls.RData"))
load(file.path(external_path, "ecls/raw_ecls.RData"))

# Corrected ECLS (Fix incorrect thetas)
corrected_ecls <- read_dta(file.path(external_path, "ecls/eclsk_theta_errata.dta"))
colnames <- sub("_r$", "", colnames(corrected_ecls))

ecls_clean <- ecls %>%
  clean_names() %>%
  left_join(corrected_ecls, by = "childid") %>%
  select(-setdiff(colnames, "childid"))  %>% # Get rid of incorrect thetas
  select(where(~ !all(is.na(.) | . == -2 | . == -9))) %>% # Omit Suppressed Columns
  mutate( 
    # Factorize and NA Demographic Variables 
    p1ageent = if_else(p1ageent <= 0, NA, p1ageent), 
    across(c(p1hfamil, p2hfamil, p4hfamil, p5hfamil, p6hfamil, p7hfamil), as.factor), 
    across(
      c(p1hmemp, p4hmemp, p5hmemp, p6hmemp, p7hmemp, # Mom Emp
        p1hdemp, p4hdemp, p5hdemp, p6hdemp, p7hdemp, # Dad Emp
        wkdaded, w1daded, w3daded, w5daded, w8daded, 
        wkmomed, w1momed, w3momed, w5momed, w8momed,
        wkraceth, w1raceth), 
      ~ if_else(.x <= 0, NA_real_, .x)
    ), 
    across(c(wkraceth, w1raceth, w1povrty, w3povrty, w5povrty, w8povrty, wkdaded, w1daded, w3daded, w5daded, w8daded,wkmomed, w1momed, w3momed, w5momed, w8momed), as.factor)
  )

# Base Year School 
school <- read_dta(file.path(external_path, "ecls/ECLSK_BaseYear_School_STATA.dta")) %>%
  clean_names() %>%
  select(where(~ !all(is.na(.) | . == -2 | . == -9)))

teacher <- read_dta(file.path(external_path, "ecls/ECLSK_BaseYear_Teacher_STATA.dta")) %>%
  clean_names()
```

# Teacher Race
```{r}
ecls_clean <- ecls_clean %>%
  mutate(
    b1raceth = case_when(
      b1race5 == 1 ~ 1,
      b1race3 == 1 ~ 2,
      b1race2 == 1 ~ 5,
      b1race1 == 1 ~ 7
    )) %>%
  mutate(
    race_match_k = as.factor(
      b1raceth == w1raceth | (b1raceth == 1) & (w1raceth == 3 | w1raceth == 4)
      )
  )
```


# Calculate School Means 
```{r}
###############################
# 0. Calculate School Means
###############################

calculate_school_means <- function(data, i, score, type) {
  if (i == 3) {
    s_id <- paste0("s", 4, "_id")
  }
  else{
    s_id <- paste0("s", i, "_id")
  }
  
  sch_mean <- paste0("sch_", type, "_mean_", i)
  
  data <- data %>%
    group_by(!!sym(s_id)) %>%
    mutate(
      not_na := n() - sum(is.na(!!sym(score))),
      !!sym(sch_mean) := if_else(not_na > 1, (sum(!!sym(score), na.rm = T) - !!sym(score)) / (not_na-1), NA_real_)
    ) %>%
    ungroup()
  
  return(data)
}

for (i in 1:7) {
  score <- paste0("c", i, "r4mscl") 
  ecls_clean <- calculate_school_means(ecls_clean, i, score, "math")
  
  score <- paste0("c", i, "r4rscl") 
  ecls_clean <- calculate_school_means(ecls_clean, i, score, "rdg")
}

for (i in c(1,2,4,5,6)) {
  score <- paste0("t", i, "interp")
  ecls_clean <- calculate_school_means(ecls_clean, i, score, "social")
  
  score <- paste0("t", i, "learn")
  ecls_clean <- calculate_school_means(ecls_clean, i, score, "learn")
}

ecls_clean <- ecls_clean %>%
  mutate(
    delta_12 = c2r4mscl - c1r4mscl, 
    delta_23 = c3r4mscl - c2r4mscl, 
    delta_34 = c4r4mscl - c3r4mscl, 
    delta_45 = c5r4mscl - c4r4mscl, 
    delta_56 = c6r4mscl - c5r4mscl, 
    delta_67 = c7r4mscl - c6r4mscl
  )

for (i in 1:6) {
  ecls_clean <- calculate_school_means(ecls_clean, i, "p1ageent", "ageent")
  
  score <- paste0("delta_", i, i+1)
  ecls_clean <- calculate_school_means(ecls_clean, i, score, score)
} 
```

# Define Control Variables for Regressions at each Grade Level 
```{r}
# Different data were collected at different rounds of data collection 
# 2,4,5,6 -- T#RTMTH 

# Grades K-3 Control Vars 
for (i in c(1,2,4,5,6)) {
  # Teacher Vars 
  assign(paste0("tch_eval_", i), c(paste0("t", i, "learn"), paste0("t", i, "extern"), paste0("t", i, "intern"), paste0("t", i, "contro"), paste0("t", i, "interp")))
  
  # Class Vars
  assign(paste0("class_eval_", i), c(paste0("class_math_mean_", i), paste0("class_rdg_mean_", i), paste0("class_interp_mean_", i), paste0("class_learn_mean_", i)))
  
  # School Vars
  assign(paste0("sch_eval_", i), c(paste0("sch_math_mean_", i), paste0("sch_rdg_mean_", i), paste0("sch_social_mean_", i), paste0("sch_learn_mean_", i)))
}

# Teacher Evaluation in Grade 8
###########
# !! Need to update by defining single variable with the second teacher's rating !! 
###########

assign(paste0("tch_eval_", 7), c("g7relwel", "g7tlkout", "g7honors", "g7wrkhrd", "g7behind", "g7attent", "g7organz"))

# Parent Evals from K-8 Grades 
for (i in c(1,4,5,6,7)) {
  # Parent Evaluations 
  if (i %in% c(1,4)) {
    assign(paste0("par_eval_", i), c(paste0("p", i, "sameag"), paste0("p", i, "learn"), paste0("p", i, "social"), paste0("p", i, "active")))
  } else if (i %in% c(5,6,7)) {
    assign(paste0("par_eval_", i), c(paste0("p", i, "sameag"), paste0("p", i, "active")))
  }
}

# Test Evals in every data collection round 
for (i in 1:7) {
  # Test Vars 
  assign(paste0("test_eval_", i), c(paste0("c", i, "r4rscl"), paste0("c", i, "r4mscl"), paste0("c", i, "r4rpf"), paste0("c", i, "r4mpf")))
}

# Controls for Teacher's Cognitive evaluations from K-8 Grade
# Depends on what data was collected 
for (i in c(2,4,5,6,7)) {
  if (i == 2) {
    assign(paste0("tch_eval_cog_", i), c(paste0("t", i, "rtmth"), paste0("t", i, "rtlang")))
  } else if (i %in% c(4,5)) {
    assign(paste0("tch_eval_cog_", i), c(paste0("t", i, "rtmth"), paste0("t", i, "rtlang"), paste0("t", i, "arsmat"), paste0("t", i, "arslit")))
  } else if (i == 6) {
    assign(paste0("tch_eval_cog_", i), c(paste0("m", i, "rtmth"), paste0("g", i, "rtlang"), paste0("t", i, "arsmat"), paste0("t", i, "arslit")))
  } else if (i == 7) {
    assign(paste0("tch_eval_cog_", i), c("t7arsmat", "t7arsorl", "t7arssci", "t7arswrt"))
  }
}

child_eval_ncog_7 <- c("c7sports", "c7trywt", "c7home", "c7angry", "c7likrd", "c7lonly", "c7flgood", "c7worth", "c7able", "c7stops", "c7noplan", "c7cherpa", "c7sdqint")
child_eval_cog_7 <- c("c7sdqmtc", "c7sdqrdc")
```


# Age of Entry Instrument (Plots)
```{r}
###############################
# 1.0 Age of Entry (First Stage)
###############################

# Good Instrument
plot <- ecls_clean %>%
  filter(s2yyfive == 1996 | s2yyfive == 1997 | s2yyfive == 1998 | s2yyfive == 1999) %>%
  mutate(
    date = as.Date(paste(s2yyfive, s2mmfive, "15", sep = "-"))
  ) %>%
  group_by(date) %>%
  summarize(
    mean_ = mean(p1ageent, na.rm = T)
  ) %>%
  ggplot(aes(x = date, y = mean_)) + 
  geom_line() + 
  labs(
    x = "Date by which child must turn five", 
    y = "Mean Entry Age (Months)", 
    title = "Kindergarten Age Rules and Entry Age",
    subtitle = "for entering class of 1998-1999"
  ) + 
  theme_minimal() +
  scale_x_date(date_labels = "%b %Y", date_breaks = "3 month") + 
  theme(
    plot.title = element_text(size = 18),  
    plot.subtitle = element_text(size = 14),            
    axis.title.x = element_text(size = 14),            
    axis.title.y = element_text(size = 14),                 
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),   
    axis.text.y = element_text(size = 12),          
    legend.title = element_text(size = 14),          
    legend.text = element_text(size = 12)    
  )

print(plot)
ggsave(file.path(output_path, "kindergarten_entry_age.png"), plot = plot, width = 8, height = 5, dpi = 300, bg = "white")

# Scatter by School 
scatter_plot <- ecls_clean %>%
  filter(s2yyfive == 1996 | s2yyfive == 1997 | s2yyfive == 1998 | s2yyfive == 1999) %>%
  mutate(
    date = as.Date(paste(s2yyfive, s2mmfive, "15", sep = "-"))
  ) %>%
  group_by(s1_id) %>%
  summarize(
    date = first(date), 
    mean_ageent = mean(p1ageent, na.rm = T), 
    n = n()
  ) %>%
  ggplot(aes(x = date, y = mean_ageent, size = n)) + 
  geom_point(color = "steelblue") + 
  theme_minimal() + 
  labs(
    x = "Date by which child must turn five", 
    y = "Mean Entry Age (Months)",
    title = "School's Kindergarten Age Rules and Mean Entry Age",
    subtitle = "For entering class of 1998-1999", 
    size = "Number of Children"
  ) + 
  scale_x_date(date_labels = "%b %Y", date_breaks = "3 month") +
  theme(
    plot.title = element_text(size = 18),  
    plot.subtitle = element_text(size = 14),            
    axis.title.x = element_text(size = 14),            
    axis.title.y = element_text(size = 14),                 
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),   
    axis.text.y = element_text(size = 12),          
    legend.title = element_text(size = 14),          
    legend.text = element_text(size = 12)    
  ) +
  scale_size_continuous(range = c(1,3)) 
  
print(scatter_plot) 
ggsave(file.path(output_path, "kindergarten_rule_scatter.png"), plot = scatter_plot, width = 8, height = 5, dpi = 300, bg = "white")

# Histogram visual 
histo_plot <- ecls_clean %>%
  filter(s2yyfive == 1996 | s2yyfive == 1997 | s2yyfive == 1998 | s2yyfive == 1999) %>%
  mutate(
    date = as.Date(paste(s2yyfive, s2mmfive, "15", sep = "-"))
  ) %>%
  group_by(date) %>%
  summarize(
    n_schools = n_distinct(s1_id, na.rm = T)
  ) %>%
  ggplot(aes(x = date, y = n_schools)) + 
  geom_bar(stat = "identity", fill = "steelblue") + 
  theme_minimal() + 
  scale_x_date(date_labels = "%b %Y", date_breaks = "3 month") + 
  labs(
    x = "Date by which child must turn five", 
    y = "Number of Schools",
    title = "Number of Schools by Kindergarten Rule Date",
    subtitle = "For entering class of 1998-1999"
  ) + 
  theme(
    plot.title = element_text(size = 18),  
    plot.subtitle = element_text(size = 14),            
    axis.title.x = element_text(size = 14),            
    axis.title.y = element_text(size = 14),                 
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),   
    axis.text.y = element_text(size = 12),          
    legend.title = element_text(size = 14),          
    legend.text = element_text(size = 12)    
  )

print(histo_plot)
ggsave(file.path(output_path, "kindergarten_rule_histogram.png"), plot = histo_plot, width = 8, height = 5, dpi = 300, bg = "white")

# Table 
table <- ecls_clean %>%
  filter(s2mmfive >= 0) %>%
  filter(s2yyfive >= 0) %>%
  select(s2mmfive, s2yyfive, p1ageent, s1_id) %>%
  mutate(
    entry_rule = paste0(s2yyfive, "-", s2mmfive)
  ) %>%
  group_by(entry_rule) %>%
  summarize(
    number_of_schools = n_distinct(s1_id)
  ) %>%
  gt() %>%
  tab_options(
    table.font.size = px(10),   
    data_row.padding = px(2),  
    heading.padding = px(4)     
  )

print(table)
gtsave(table, filename = file.path(output_path, "kindergarten_rule_table.png"))

# Check NA's 
check_na(ecls_clean, c("s2"))
```

# Age of Entry Instrument (Check Balance)
```{r}
##################################
# 1.1 Age of Entry (Balance Check)
##################################

balance_df <- ecls_clean %>%
  filter(if_all(c(s2yyfive, s2mmfive, s2ddfive), ~ . >= 0)) %>%
  mutate(
    entry_rule = as.Date(sprintf("%04d-%02d-%02d", s2yyfive, s2mmfive, s2ddfive)), 
    dob = as.Date(sprintf("%04d-%02d-%02d", dobyy, dobmm, dobdd)), 
    when_five = dob + years(5)
  ) %>% 
  group_by(entry_rule) %>%
  mutate(
    interval = case_when(
      when_five <= entry_rule & abs(as.numeric(entry_rule - when_five)) <= 90 ~ "before", 
      when_five > entry_rule - years(1) & abs(as.numeric(when_five - (entry_rule - years(1)))) <= 90 ~ "after", 
      TRUE ~ "not_in"
    ), 
    interval = as.factor(interval)
  )

# Add Optionally 
# when_five > entry_rule & abs(as.numeric(when_five - entry_rule)) <= 60 | 

table <- balance_df %>%
  group_by(interval) %>%
  summarize(
    "Mean Age of Entry (Months)" = mean(p1ageent, na.rm = T), 
    "Median Age of Entry (Months)" = quantile(p1ageent, 0.5, na.rm = T), 
    "Household Income (K Fall)" = mean(wkincome, na.rm = T), 
    "Household Income (K Spring)" = mean(w1income, na.rm = T), 
    "Dad Occupation Prestige" = mean(w1dadscr, na.rm = T), 
    "Mom Occupation Prestige" = mean(w1momscr, na.rm = T), 
    "Poverty Level" = mean(as.numeric(w1povrty), na.rm = T),
    "School Math Scores" = mean(sch_math_mean_1, na.rm = T), 
    "Dad's Level of Education" = mean(as.numeric(w1daded), na.rm = T), 
    "Mom's Level of Education" = mean(as.numeric(w1momed), na.rm = T), 
    "Child's Own Math Score" = mean(c1r4mscl, na.rm = T),
    "N" = n()
  ) %>%
  mutate(
    across(
      .cols = -c(interval), 
      .fns = ~ round(.x, 2)
    )
  ) %>%
  pivot_longer(
    cols = -interval,
    names_to = "variable",
    values_to = "value"
  ) %>%
  pivot_wider(
    names_from = interval, 
    values_from = value
  )

table_gt <- table %>%
  gt() %>%
  tab_header(
    title = "Balance on Observables for Birthday's falling before or after entry rule (± two months)", 
    subtitle = "Children who are delayed by close to one year are similar to children who enter early"
  ) %>%
  cols_label(
    variable = "Mean Summary Statistic",
    before = "Before (≤ 60 days)",
    after = "After (≤ 60 days)",
    not_in = "Outside 4-month Window"
  ) %>%
  tab_source_note(
    source_note = "Note: All means are rounded to 2 decimal places and calculated by interval. N represents the number of observations. Importantly, 'After' includes children whose fifth birthdays fall AFTER the entry rule - 1 (could not enroll in the previous year), while 'Before' denotes children who turned 5 within 2 months before the entry rule. 'Mean school math 1' denotes the average math score of peers in the kindergarten eventually enrolled, while 'Mean math 1' denotes the average kindergarten math scores for children in the interval."
  )

print(table_gt)
gtsave(table_gt, filename = file.path(output_path, "kindergarten_rule_table.png"))
# Also need to check against (1) When the assessment was administered, and (2) When the schools opened / when the school year started. 
```

# Age of Assessment 
```{r}
assmtmm_plot <- ecls_clean %>%
  filter(!is.na(c1asmtmm)) %>%
  mutate(c1asmtmm = as.Date(paste0("1998-", c1asmtmm, "-01"))) %>%
  group_by(c1asmtmm) %>%
  summarize(
    n = n(), 
    mean_math = mean(c1r4mscl, na.rm = T)
  ) %>%
  ggplot(aes(x = c1asmtmm, y = mean_math, size = n)) + 
  geom_point(color = "steelblue") + 
  theme_minimal() + 
  scale_size_continuous(range = c(3,6)) + 
  labs(
    x = "Assesment Month", 
    y = "Mean Math Score", 
    title = "Test Scores Increase with Assessment Month"
  )

print(assmtmm_plot)
ggsave(file.path(output_path, "assmtmm_plot.png"), plot = assmtmm_plot, width = 8, height = 5, dpi = 300, bg = "white")

```

# First Stage 
```{r}
# Filter for the interval and recode to dummy instrument 
balance_df_interval <- balance_df %>%
  filter(interval != "not_in") %>%
  mutate(interval = case_when(
    interval == "before" ~ 0, 
    interval == "after" ~ 1
  ))
  
# Subset by +- two months before and after the cutoff 
model_fs_1 <- lm(p1ageent ~ interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl , data = balance_df_interval)
summary(model_fs_1)

se_fs_1 = sqrt(diag(vcovCL(model_first_stage, cluster = ~ s1_id)))

model_fs_2 <- lm(p1ageent ~ interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1 , data = balance_df_interval)
summary(model_fs_2)

se_fs_2 = sqrt(diag(vcovCL(model_fs_2, cluster = ~ s1_id)))
# Being above the interval raises your entry month by around 9 months. Consistent with our table / the simple difference in means! 

stargazer(
  model_fs_1, model_fs_2, 
  se = list(se_fs_1, se_fs_2), 
  type = "latex", 
  title = "First Stage OLS", 
  out.header = FALSE, 
  star.cutoffs = c(0.05), 
  digits = 2, 
  omit = c("p1hfamil", "w1raceth", "wkincome", "p1hmemp", "p1hdemp", "w1momed", "w1daded", "p1numsib", "w1dadscr", "w1momscr", "p1disabl", "sch_math_mean_1"), 
  add.lines = list(
    c("SES Control", "Yes", "Yes"), 
    c("School Math Mean Control", "No", "Yes"), 
    c("\\hline", "", "")
  ), 
  dep.var.labels.include = TRUE,
  dependent.var.labels = c("Age of Entry (Months)"),
  covariate.labels = c("birthday past cutoff", "first time kindergartener")
)
```
# Reduced Form
```{r}
model_rf_1 <- lm(c1r4mscl ~ interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl , data = balance_df_interval)
summary(model_rf_1) 

se_rf_1 <- sqrt(diag(vcovCL(model_rf_1, cluster = ~ s1_id)))

model_rf_2 <- lm(c1r4mscl ~ interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1, data = balance_df_interval)

se_rf_2 <- sqrt(diag(vcovCL(model_rf_2, cluster = ~ s1_id)))

model_rf_3 <- lm(c1r4rscl ~ interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl , data = balance_df_interval)
summary(model_rf_3) 

se_rf_3 <- sqrt(diag(vcovCL(model_rf_3, cluster = ~ s1_id)))

model_rf_4 <- lm(c1r4rscl ~ interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1, data = balance_df_interval)

se_rf_4 <- sqrt(diag(vcovCL(model_rf_4, cluster = ~ s1_id)))

stargazer(
  model_rf_1, model_rf_2, model_rf_3, model_rf_4,
  se = list(se_rf_1, se_rf_2, se_rf_3, se_rf_4), 
  type = "latex", 
  title = "Reduced Form OLS", 
  out.header = FALSE, 
  star.cutoffs = c(0.05), 
  digits = 2, 
  omit = c("p1hfamil", "w1raceth", "wkincome", "p1hmemp", "p1hdemp", "w1momed", "w1daded", "p1numsib", "w1dadscr", "w1momscr", "p1disabl", "sch_math_mean_1"), 
  add.lines = list(
    c("SES Control", "Yes", "Yes", "Yes", "Yes"), 
    c("School Math Mean Control", "No", "Yes", "No", "Yes"), 
    c("\\hline", "", "", "", "")
  ), 
  dep.var.labels.include = TRUE,
  dependent.var.labels = c("Kindergarten Math Score"),
  covariate.labels = c("birthday past cutoff", "first time kindergartener"), 
  omit.stat = c("ser")
)
```
```{r}
balance_df_interval <- balance_df_interval %>%
  mutate(
    s1_id = as.factor(s1_id),
    w1dadscr = as.numeric(w1dadscr), 
    w1momscr = as.numeric(w1momscr)
  )

#####################
# IV / TSLS Regression
#####################

model_iv_math <- ivreg(c1r4mscl ~ p1ageent + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1 | interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1 , data = balance_df_interval)

se_iv_math <- sqrt(diag(vcovCL(model_iv_math, cluster = ~ s1_id)))

model_iv_reading <- ivreg(c1r4rscl ~ p1ageent + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1 | interval + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1 , data = balance_df_interval)

se_iv_reading <- sqrt(diag(vcovCL(model_iv_reading, cluster = ~ s1_id)))

#####################
# OLS Regression
#####################

model_ols_math <- lm(c1r4mscl~ p1ageent + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1, data = ecls_clean)

se_ols_math <- sqrt(diag(vcovCL(model_ols_math, cluster = ~ s1_id)))

model_ols_reading <- lm(c1r4rscl ~ p1ageent + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1, data = ecls_clean)

se_ols_reading <- sqrt(diag(vcovCL(model_ols_reading, cluster = ~ s1_id)))
```


# Automate Regress
```{r}
#####################
# IV / TSLS Regression
#####################

run_iv <- function(outcome_var, covar_list) {
  formula_str <- paste0(
    outcome_var, 
    "~", covar_list, "| interval +" , covar_list
  )
  
  model_iv <- ivreg(as.formula(formula_str), data = balance_df_interval)
  
  se_iv <- sqrt(diag(vcovCL(model_iv, cluster = ~ s1_id)))
  
  return(list(model_iv, se_iv))
}

covar_list <- "p1ageent + p1hfamil + w1raceth + wkincome + p1hmemp + p1hdemp + p1numsib + w1momed + w1daded + w1dadscr + w1momscr + p1firkdg + p1disabl + sch_math_mean_1"

model_iv_math <- run_iv("c1r4mscl", covar_list)[[1]]
se_iv_math <- run_iv("c1r4mscl", covar_list)[[2]]

#####################
# OLS Regression
#####################

run_ols <- function(outcome_var, covar_list) {
  formula_str <- paste0(
    outcome_var, "~", 
    covar_list
  )
  
  model_ols <- lm(as.formula(formula_str), data = balance_df_interval)
  
  se_ols <- sqrt(diag(vcovCL(model_ols, cluster = ~ s1_id)))
  
  return(list(model_ols, se_ols))
}

model_ols_math <- run_ols("c1r4mscl", covar_list)[[1]]
se_ols_math <- run_ols("c1r4mscl", covar_list)[[2]]
```


```{r}
############################
# OLS / IV Regression Table
############################

regression_table <- stargazer(model_iv_math, model_ols_math, model_iv_reading, model_ols_reading, 
          se = list(se_iv_math, se_ols_math, se_iv_reading, se_ols_reading), 
          type = "latex", 
          title = "IV and OLS Estimates of Impact of Older Kindergarten Entry on Test Scores",
          out.header = FALSE,
          star.cutoffs = c(0.05), 
          digits = 2, 
          omit = c("p1hfamil", "w1raceth", "wkincome", "p1hmemp", "p1hdemp", "w1momed", "w1daded", "p1numsib", "w1dadscr", "w1momscr", "p1disabl", "sch_math_mean"), 
          add.lines = list(
            c("SES Control", "Yes", "Yes", "Yes", "Yes"), 
            c("School Math Mean control", "Yes", "Yes", "Yes", "Yes"), 
            c("\\hline", "", "", "", "")
          ), 
          covariate.labels = c("Age of Entry (Months)", "First Time Kindergartener"), 
          column.labels = c("IV", "OLS", "IV", "OLS")
)
writeLines(regression_table, file.path(output_path, "regression_table.tex"))
```


# Fade-out of Math Score Boost over Time 
```{r}
############################
# Math Score Fade-Out
############################

for (i in 1:7) { 
  # run model
  model_output <- run_iv(paste0("c", i, "r4mscl"), covar_list)
  
  assign(paste0("model_iv_", i), model_output[[1]])
  assign(paste0("se_iv_", i), model_output[[2]])
}

models <- list(model_iv_1, model_iv_2, model_iv_3, model_iv_4, model_iv_5, model_iv_6, model_iv_7)
se_list <- list(se_iv_1, se_iv_2, se_iv_3, se_iv_4, se_iv_5, se_iv_6, se_iv_7)

stargazer(
  models,
  #model_iv_2, model_iv_3, model_iv_4, model_iv_5, model_iv_6, model_iv_7, 
  se = se_list,
  type = "latex", 
  title = "Fade-out of Entry Age Effect on Test Scores", 
  out.header = FALSE, 
  star.cutoffs = c(0.05), 
  digits = 2, 
  omit = c("p1hfamil", "w1raceth", "wkincome", "p1hmemp", "p1hdemp", "w1momed", "w1daded", "p1numsib", "w1dadscr", "w1momscr", "p1disabl", "sch_math_mean", "Constant"), 
  add.lines = list(
            c("SES Control", rep("Yes", 7)), 
            c("School Math Mean control", rep("Yes", 7)), 
            c("\\hline", rep("", 7))
          ), 
  covariate.labels = c("Age of Entry (Months)", "First Time Kindergartener"), 
  column.labels = c("K Fall", "K Spring", "1st Fall", "1st Spring", "3rd Spring", "5th Spring", "8th Spring")
)

############################
# Reading Score Fade-Out
############################

for (i in 1:7) { 
  # run model
  model_output <- run_iv(paste0("c", i, "r4rscl"), covar_list)
  
  assign(paste0("model_iv_", i), model_output[[1]])
  assign(paste0("se_iv_", i), model_output[[2]])
}

models <- list(model_iv_1, model_iv_2, model_iv_3, model_iv_4, model_iv_5, model_iv_6, model_iv_7)
se_list <- list(se_iv_1, se_iv_2, se_iv_3, se_iv_4, se_iv_5, se_iv_6, se_iv_7)

stargazer(
  models,
  #model_iv_2, model_iv_3, model_iv_4, model_iv_5, model_iv_6, model_iv_7, 
  se = se_list,
  type = "latex", 
  title = "Fade-out of Entry Age Effect on Test Scores", 
  out.header = FALSE, 
  star.cutoffs = c(0.05), 
  digits = 2, 
  omit = c("p1hfamil", "w1raceth", "wkincome", "p1hmemp", "p1hdemp", "w1momed", "w1daded", "p1numsib", "w1dadscr", "w1momscr", "p1disabl", "sch_math_mean", "Constant"), 
  add.lines = list(
            c("SES Control", rep("Yes", 7)), 
            c("School Math Mean control", rep("Yes", 7)), 
            c("\\hline", rep("", 7))
          ), 
  covariate.labels = c("Age of Entry (Months)", "First Time Kindergartener"), 
  column.labels = c("K Fall", "K Spring", "1st Fall", "1st Spring", "3rd Spring", "5th Spring", "8th Spring")
)

############################
# Graph Fade-out 
############################
coef_iv <- rep(0, 7)

coef_df <- data.frame(
  grade = (1:7), 
  coef_iv = coef_iv   
)

for (i in 1:7) {
  coef_df$coef_iv[i] <- coef(get(paste0("model_iv_", i)))[["p1ageent"]]
}

coef_df$grade <- factor(coef_df$grade, 
                        levels = 1:7, 
                        labels = c("K Fall", "K Spring", "1st Fall", "1st Spring", "3rd Spring", "5th Spring", "8th Spring"))


iv_plot <- ggplot(aes(x = grade, y = coef_iv), data = coef_df) + 
  geom_point(color = "steelblue") + 
  geom_line(color = "steelblue", aes(group = 1)) + 
  theme_minimal() + 
  labs(
    title = "Effect of Earlier Entry on Math IRT Scores Across Grades", 
    x = "Data Collection Round", 
    y = "IV Coefficient" 
  ) + 
  theme(
    axis.text.x = element_text(margin = margin(t = 10)), 
    axis.title.x = element_text(margin = margin(t = 20))
    )

ggsave(file.path(output_path, "iv_plot_math.png"), plot = iv_plot, width = 8, height = 5, dpi = 300, bg = "white")
```


```{r}
model_honors <- run_iv("p7sameag", covar_list)
model <- model_honors[[1]]
se <- model_honors[[2]]


stargazer(
  model, 
  se = list(se),
  type = "latex", 
  title = "Fade-out of Entry Age Effect on Test Scores", 
  out.header = FALSE, 
  star.cutoffs = c(0.05), 
  digits = 2, 
  omit = c("p1hfamil", "w1raceth", "wkincome", "p1hmemp", "p1hdemp", "w1momed", "w1daded", "p1numsib", "w1dadscr", "w1momscr", "p1disabl", "sch_math_mean", "Constant")
)
```

```{r}
# Huge effect on p4learn and t4interp, learn, extern, 
# And also t6learn! 
# As well as M6RTMTH 


model <- lm(p4learn ~ p1hfamil + w1raceth + w1momed + w1daded + s2mmfive * after_7 + p1firkdg + sch_math_mean_1, data = jk)
summary(model)

summary(ecls_clean$c6r4mscl)

jk %>%
  select(matches("firk"))

ecls_clean %>%
  group_by(s2mmfive, s2yyfive) %>%
  filter(s2yyfive >= 1997) %>%
  summarize(
    mean = mean(p1ageent, na.rm = T), 
    n = n()
  )


ecls_clean %>%
  group_by(s2mmfive, s2yyfive) %>%
  filter(s2yyfive >= 1997) %>%
  summarize(
    mean = mean(p1ageent, na.rm = T), 
    n = n()
  )

table(ecls_clean$s2mmfive)

table(ecls_clean$u4schbmm)

ecls_clean %>%
  group_by(s1_id) %>%
  summarize(
    n = n_distinct(childid)
  )

head(ecls_clean)
```

```{r}
########################## 
# 0. Variables of Interest 
########################## 

colnames <- names(ecls_clean)

# By-Grade SES Vars 
# SES is the only variable coded by grade level, which is consistent with the ECLS 
for (i in c(1,3,5,8)) {
  assign(paste0("ses_vars_", i), c(paste0("w", i, "momed"),
                                   paste0("w", i, "daded"),
                                   paste0("w", i, "momscr"),
                                   paste0("w", i, "dadscr"),
                                   paste0("w", i, "povrty"),
                                   paste0("w", i, "disabl"),
                                   paste0("w", i, "raceth")))
}

# Other Vars by Data Collection Round 
for (i in c(1,2,4,5,6,7)) {
  assign(paste0("fam_vars", i), c(paste0("p", i, "hfamil"), 
                                  paste0("p", i, "hmemp"), 
                                  paste0("p", i, "hdemp"), 
                                  paste0("p", i, "numsib"))
         )
}
      
child_vars <- c("p1ageent", "p1agefrs", "w1raceth", "p1firkdg", "p1center")

tch_vars <- c("b1behvr", "b1yrskin", "b1yrsch", "b1notcap", "race_match_k")
```






```{r}
########################## 
# 1. Run Regressions 
########################## 

paste_lm <- function(var_name) {
  return(paste(var_name, collapse = "+"))
}

for (i in seq_along(test_eval_2)) {
  cat("############### \n OUTCOME VARIABLE:", test_eval_2[i], "\n###############")
  
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(par_eval_1), paste_lm(tch_eval_1), paste_lm(class_eval_1), paste_lm(sch_eval_1), paste_lm(test_eval_1)), collapse = "+")
  
  formula <- as.formula(paste(paste(test_eval_2[i], "~"),
                              patterns))
  model <- lm(formula, data = ecls_clean_exp)
  
  print(summary(model))
}

for (i in seq_along(tch_eval_1)) {
  cat("############### \n OUTCOME VARIABLE:", tch_eval[i], "\n###############")
  tch_eval <- setdiff(tch_eval_1, tch_eval_1[i])
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(tch_vars), paste_lm(par_eval_1), paste_lm(tch_eval), paste_lm(class_eval_1), paste_lm(sch_eval_1)), collapse = "+")
  
  formula <- as.formula(paste0(paste(tch_eval_1[i], "~"),
                               patterns)) 
  model <- lm(formula, data = ecls_clean_exp) 
  print(summary(model))
}

for (i in seq_along(par_eval_1)) {
  cat("############### \n OUTCOME VARIABLE:", par_eval_1[i], "\n###############") 
  
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(tch_vars), paste_lm(tch_eval), paste_lm(class_eval_1), paste_lm(sch_eval_1), paste_lm(test_eval_1)), collapse = "+")
  
  formula <- as.formula(paste0(paste(par_eval_1[i], "~"), 
                        patterns))
  
  model <- lm(formula, data = ecls_clean_exp)
  print(summary(model))
}

patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(par_eval_4), paste_lm(class_eval_5), paste_lm(sch_eval_5), paste_lm(test_eval_7), paste_lm(child_eval_ncog_7)), collapse = "+")

```


```{r}
##########################
# 2. Entry Age and other Factors
##########################

formula <- as.formula(paste("sch_math_mean_5 ~", paste(c("sch_delta_45_mean_4", "sch_math_mean_4", "sch_ageent_mean_1"), collapse = "+")))
mod <- lm(formula, data = ecls_clean_exp)
summary(mod)

formula <- as.formula(paste("c1r4rtsc ~", paste(c(paste_lm(child_vars), paste_lm(ses_vars), paste_lm(school_eval_1), "sch_ageent_mean_4", "sch_income_mean_4", "sch_par1ed_mean_4", "sch_par2ed_mean_4", "x2mscalk5"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

formula <- as.formula(paste("p1ageent ~ ", paste(c(paste_lm(child_vars), paste_lm(ses_vars), paste_lm(sch_eval_1), "sch_ageent_mean_1",  "sch_delta_12_mean_1"), collapse = "+")))
mod <- lm(formula, data = ecls_clean_exp)
summary(mod)

formula <- as.formula(paste("sch_math_mean_1 ~ ", paste(c("sch_ageent_mean_1", "sch_income_mean_1", "sch_par1ed_mean_1", "sch_par2ed_mean_1", "sch_delta_12_mean_1"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

```

# ECLS 2011 
```{r}
##########################
# Set up
##########################

ecls_new <- read_dta(file.path(external_path, "ecls_2011/ECLSK2011_K5PUF.dta"))
save(ecls_new, file = file.path(external_path, "ecls_2011/raw_ecls_new.RData"))
load(file.path(external_path, "ecls_2011/raw_ecls_new.RData"))

ecls_new_clean <- ecls_new %>% 
  clean_names() %>%
  select(where(~ !all(is.na(.) | . == -2 | . == -9))) %>%
  mutate(
    across(
      c(x1hparnt, x2hparnt, x4hparnt, x5hparnt, x6hparnt, x7hparnt, x8hparnt, x9hparnt, 
        x1par1emp, x4par1emp, x6par1emp, x9par1emp, 
        x1par2emp, x4par2emp, x6par2emp, x9par2emp, 
        x_raceth_r, 
        x12par1ed_i, x4par1ed_i, x7par1ed_i, x8par1ed_i, x9par1ed_i, 
        x12par2ed_i, x4par2ed_i, x7par2ed_i, x8par2ed_i, x9par2ed_i, 
        x2povty, x4povty_i, x6povty_i, x7povty_i, x8povty_i, x9povty_i), 
      as.factor()
    ), 
    across(
      c(x1hparnt, x2hparnt, x4hparnt, x5hparnt, x6hparnt, x7hparnt, x8hparnt, x9hparnt, 
        x1par1emp, x4par1emp, x6par1emp, x9par1emp, 
        x1par2emp, x4par2emp, x6par2emp, x9par2emp, 
        x_raceth_r, 
        x12par1ed_i, x4par1ed_i, x7par1ed_i, x8par1ed_i, x9par1ed_i, 
        x12par2ed_i, x4par2ed_i, x7par2ed_i, x8par2ed_i, x9par2ed_i, 
        x2povty, x4povty_i, x6povty_i, x7povty_i, x8povty_i, x9povty_i), 
      ~ if_else(.x <= 0, NA_real_, .x)
    )
  )

for (i in c(1,2,4,6,7,8,9)) {
  score <- paste0("x", i, "rscalk5") 
  
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, score, "rdg")
  
  score <- paste0("x", i, "mscalk5") 
  
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, score, "math")
  
  score <- paste0("x", i, "tchper") 
  
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, score, "social")
}

ecls_new_clean_exp <- ecls_new_clean_exp %>%
  mutate(
    delta_12 = x2mscalk5 - x1mscalk5, 
    delta_23 = x3mscalk5 - x2mscalk5, 
    delta_34 = x4mscalk5 - x3mscalk5, 
    delta_45 = x5mscalk5 - x4mscalk5, 
    delta_56 = x6mscalk5 - x5mscalk5, 
    delta_67 = x7mscalk5 - x6mscalk5, 
    delta_78 = x8mscalk5 - x7mscalk5
  )

for (i in c(1,2,4,6,7)) {
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, "x1ageent", "ageent")
  
  score <- paste0("delta_", i, i+1)
  
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, score, score)
  
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, "x2inccat_i", "income")
  
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, "x12par1ed_i", "par1ed")
  
  ecls_new_clean_exp <- calculate_school_means(ecls_new_clean_exp, i, "x12par2ed_i", "par2ed")
}


```


```{r}
##########################
# 0. Variables of Interest 
##########################

child_vars <- c("x1ageent", "x_raceth_r", "x2disabl")

ses_vars <- c("x1par1emp", "x1par2emp", "x2numsib", "x12par1ed_i", "x12par2ed_i", "x1par1scr_i", "x1par2scr_i", "x2inccat_i", "x2povty")

for (i in 1:9) {
  # Test Scores 
  assign(paste0("test_eval_", i), c(paste0("x", i, "rscalk5"), paste0("x", i, "mscalk5") ))
  
  # Teacher Evals
  assign(paste0("tch_eval_", i), c(paste0("x", i, "tchcon"), paste0("x", i, "tchper"), paste0("x", i, "tchext"), paste0("x", i, "tchint"), paste0("x", i, "tchapp")))
  
  # More Teacher Evals 
  if (i %in% c(1,2,3,5,6,7)) {
    assign(paste0("tch_eval_", i), c(get(paste0("tch_eval_", i)), c(paste0("t", i, "works"), paste0("t", i, "shows"), paste0("t", i, "follow"), paste0("t", i, "atten"))))
  }
}

for (i in c(7,8,9)) {
  assign(paste0("child_eval_", i), c(paste0("c", i, "teased"), paste0("c", i, "excldch"), paste0("c", i, "wrythk"), paste0("c", i, "afrdntlk"), paste0("c", i, "wrydtlk")))
  
  if (i == 7) {
    assign("child_eval_7", c(get("child_eval_7"), c("c7gdread", "c7enjread", "c7enjmth", "c7gdmth", "c7hasfrnds", "c7easylik", "c7morfrnd", "c7cheerup", "c7niceoth")))
  }
  
  if (i %in% c(8,9)) {
    assign(paste0("child_eval_", i), c(get(paste0("child_eval_", i)), c(paste0("c", i, "wrkhrd"), paste0("c", i, "kidply"), paste0("c", i, "lonely"), paste0("c", i, "lftout"))))
  }
}

for (i in c(1,2,4)) {
  # Parent Evals 
  assign(paste0("par_eval_", i), c(paste0("x", i, "prnapp"), paste0("x", i, "prncon"), paste0("x", i, "prnsoc"), paste0("x", i, "prnsad")))
}

for (i in c(1,2,4,6,7,8,9)) {
  assign(paste0("school_eval_", i), c(paste0("sch_math_mean_", i), paste0("sch_social_mean_", i), paste0("sch_rdg_mean_", i)))
}
```


```{r}
##########################
# 1. Run Regressions  
##########################

ecls_new_clean_exp <- ecls_new_clean_exp %>%
  filter(if_all(all_of(tch_eval_4), ~ . >= 0), 
         if_all(all_of(tch_eval_2), ~ . >= 0),
         if_all(all_of(par_eval_2), ~ . >= 0),
         if_all(all_of(par_eval_4), ~ . >= 0)) %>%
  mutate(x1par1emp = as.factor(x1par1emp), 
         x1par2emp = as.factor(x1par2emp))

ecls_new_clean_exp <- ecls_new_clean_exp %>%
  filter(if_all(all_of(child_eval_7), ~. >= 0)) %>%
  mutate(x1par1emp = as.factor(x1par1emp), 
         x1par2emp = as.factor(x1par2emp))

for (i in seq_along(test_eval_4)) {
  cat("######################## \n", "OUTCOME VARIABLE: ", test_eval_4[i], " \n#######################")
  
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(school_eval_4), paste_lm(test_eval_2), paste_lm(tch_eval_2)), collapse = "+")
  
  formula <- as.formula(paste0(paste0(test_eval_4[i], "~"), 
                               patterns))
  
  model <- lm(formula, data = ecls_new_clean_exp)
  
  print(summary(model))
}

for (i in seq_along(tch_eval_4)) {
  cat("######################## \n", "OUTCOME VARIABLE: ", tch_eval_4[i], " \n#######################")
  
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(school_eval_2), paste_lm(par_eval_4), paste_lm(test_eval_4), paste_lm(test_eval_2), paste_lm(tch_eval_2)), collapse = "+") 
  
  formula <- as.formula(paste0(paste0(tch_eval_4[i], "~"), 
                               patterns)
                        )
  
  model <- lm(formula, data = ecls_new_clean_exp)
  
  print(summary(model))
}


for (i in seq_along(par_eval_4)) {
  cat("######################## \n", "OUTCOME VARIABLE: ", par_eval_4[i], " \n#######################")
  
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(school_eval_4), paste_lm(par_eval_2), paste_lm(test_eval_4), paste_lm(tch_eval_2)), collapse = "+") 
  
  formula <- as.formula(paste0(paste0(par_eval_4[i], "~"), 
                               patterns)
                        )
  
  model <- lm(formula, data = ecls_new_clean_exp)
  
  print(summary(model))
}

for (i in seq_along(child_eval_7)) {
  cat("######################## \n", "OUTCOME VARIABLE: ", child_eval_7[i], " \n#######################")
  
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(school_eval_6), paste_lm(par_eval_4), paste_lm(test_eval_6), paste_lm(tch_eval_5)), collapse = "+") 
  
  formula <- as.formula(paste0(paste0(child_eval_7[i], "~"), 
                               patterns)
                        )
  
  model <- lm(formula, data = ecls_new_clean_exp)
  
  print(summary(model))
}

paste("")
```

```{r}
##########################
# 1. Run Regressions  
##########################

ecls_new_clean_exp <- ecls_new_clean_exp %>%
  mutate(across(all_of(child_eval_7), as.numeric)) %>%
  filter(if_all(all_of(child_eval_7), ~. != -7 & . != -9))

for (i in seq_along(child_eval_7)) {
  cat("######################## \n", "OUTCOME VARIABLE: ", child_eval_7[i], " \n#######################")
  
  patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(school_eval_6), paste_lm(par_eval_4), paste_lm(test_eval_6), paste_lm(tch_eval_5)), collapse = "+") 
  
  formula <- as.formula(paste0(paste0(child_eval_7[i], "~"), 
                               patterns)
                        )
  
  model <- multinom(formula, data = ecls_new_clean_exp)
  
  print(summary(model))
}

child_eval_7


cat("######################## \n", "OUTCOME VARIABLE: ", "gdread", " \n#######################")
  
patterns <- paste(c(paste_lm(ses_vars), paste_lm(child_vars), paste_lm(school_eval_6), paste_lm(test_eval_7), paste_lm(tch_eval_5)), collapse = "+") 
  
formula <- as.formula(paste0(paste0("c7gdread", "~"), 
                               patterns)
                        )
  
model <- multinom(formula, data = ecls_new_clean_exp, maxit = 500)
model_summary <- summary(model)
vif(model)

z_values <- model_summary$coefficients / model_summary$standard.errors
p_values <- 2 * (1 - pnorm(abs(z_values)))
print(p_values)
ses_vars

paste("")
```

```{r}
##########################
# 1. Entry Age and other Factors
##########################

ecls_new_clean_exp <- ecls_new_clean_exp %>%
  filter(x1ageent >= 0 & x1mscalk5 >= 0 & x2mscalk5 >= 0)

ggplot(ecls_new_clean_exp) + 
  geom_histogram(aes(x = x1ageent), bins = 50)

summary(ecls_new_clean_exp$x1ageent)


ecls_new_clean_exp %>%
  filter(delta_12 <= -10)

summary(ecls_new_clean_exp$delta_12)

 
 
formula <- as.formula(paste("x2mscalk5 ~", paste(c(paste_lm(child_vars), paste_lm(ses_vars), paste_lm(school_eval_1), "x1mscalk5",  "sch_math_mean_1", "sch_income_mean_2", "sch_par1ed_mean_2", "sch_par2ed_mean_2"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

formula <- as.formula(paste("sch_delta_78_mean_7 ~", paste(c(paste_lm(school_eval_1), "x7mscalk5",  "sch_math_mean_7", "sch_income_mean_6", "sch_par1ed_mean_6", "sch_par2ed_mean_6", "sch_delta_67_mean_6"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)


```

```{r}
formula <- as.formula(paste("sch_delta_12_mean_1 ~", paste(c(paste_lm(child_vars), paste_lm(ses_vars), paste_lm(school_eval_1), "x1mscalk5",  "sch_math_mean_1", "sch_income_mean_2","sch_ageent_mean_2", "sch_par1ed_mean_2", "sch_par2ed_mean_2"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

```


```{r}
formula <- as.formula(paste("x3tchper ~", paste(c(paste_lm(child_vars), paste_lm(ses_vars), paste_lm(school_eval_2), "sch_ageent_mean_2", "sch_income_mean_2", "sch_par1ed_mean_2", "sch_par2ed_mean_2", paste_lm(par_eval_2), "x2tchper"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

par_eval_2
tch_eval_2
```

```{r}
formula <- as.formula(paste("x1ageent ~ ", paste(c(paste_lm(child_varss), paste_lm(ses_vars), paste_lm(school_eval_1), "sch_ageent_mean_1", "sch_income_mean_1", "sch_par1ed_mean_1",  "sch_par2ed_mean_1", "sch_delta_12_mean_1", "x1par1emp", "x1par2emp"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

formula <- as.formula(paste("sch_math_mean_1 ~ ", paste(c("sch_ageent_mean_1", "sch_income_mean_1", "sch_par1ed_mean_1", "sch_par2ed_mean_1", "sch_delta_12_mean_1"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

summary(ecls_new_clean_exp$x1mscalk5)

formula <- as.formula(paste("x2mscalk5 ~", paste(c(paste_lm(child_vars), paste_lm(ses_vars), paste_lm(school_eval_1), "sch_ageent_mean_1", "sch_delta_12_mean_1", "sch_math_mean_1"), collapse = "+")))
mod <- lm(formula, data = ecls_new_clean_exp)
summary(mod)

ecls_new_clean_exp %>%
  select(matches("delta_12"))

```

```{r}

ggplot(data = ecls_new_clean_exp %>%
         mutate(
           quantile_group = cut(
             x1ageent,
             breaks = quantile(x1ageent, probs = seq(0, 1, by = 0.1), na.rm = TRUE),
             include.lowest = TRUE,
             labels = 1:10
    )) %>%
         group_by(quantile_group) %>%
         summarize(
           mean_1 = mean(x1mscalk5, na.rm = T), 
           mean_2 = mean(x2mscalk5, na.rm = T), 
           mean_3 = mean(x3mscalk5, na.rm = T), 
           mean_4 = mean(x4mscalk5, na.rm = T), 
           mean_5 = mean(x5mscalk5, na.rm = T), 
           mean_6 = mean(x6mscalk5, na.rm = T), 
           mean_7 = mean(x7mscalk5, na.rm = T)
         ) %>%
      mutate(
        quantile_group = as.numeric(as.character(quantile_group))
      )) + 
  geom_line(aes(x = quantile_group, y = mean_7)) +
  labs(
    x = "Kindergarten Starting Age (Mths)", 
    y = "Mean Math Scores", 
    title = "Cross-sectional relationship between starting age and achievement"
  ) +
  theme_minimal()

summary(ecls_new_clean_exp$x1ageent)


ggplot(data = ecls_new_clean_exp %>%
         mutate(
           quantile_group = cut(
             x1ageent,
             breaks = quantile(x1ageent, probs = seq(0, 1, by = 0.025), na.rm = TRUE),
             include.lowest = TRUE,
             labels = 1:40
    )) %>%
         group_by(quantile_group) %>%
         summarize(
           mean_1 = mean(sch_math_mean_1, na.rm = T), 
           mean_2 = mean(sch_math_mean_2, na.rm = T), 
           #mean_3 = mean(sch_ageent_mean_3, na.rm = T), 
           mean_4 = mean(sch_math_mean_4, na.rm = T), 
           mean_6 = mean(sch_math_mean_6, na.rm = T)
         ) %>%
      mutate(
        quantile_group = as.numeric(as.character(quantile_group))
      ) %>%
      filter(quantile_group >= 5)) + 
  geom_line(aes(x = quantile_group, y = mean_4)) +
  theme_minimal()

```




